### ISSUE TITLE
Create a script or program that can automatically generate all XML comments markup for all public members in any library 

### ISSUE THREAD

**Issue by Konard** [linksplatform/Data.Doublets#226]
300 RUB reward can be claimed by anyone who completes this task.

**Comment by Konard** [comment]
[GhostDoc Community](https://submain.com/ghostdoc/editions/) can be tested on how well it fits the task.

**Comment by Konard** [comment]
I also recommend checking these open source tools:
- https://github.com/jinyafeng/DocumentationAssistant
- https://github.com/seaeagle1/XDG
- https://github.com/p1va/dotnet-document
- https://github.com/bauermaximilian/DocSnippets
- https://github.com/davidgraeff/VisualStudioExtensionCppCommentStubs

**Comment by Konard** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/

**Comment by FreePhoenix888** [comment]
sh script to remove xml docs for private classes, methods

**Comment by Konard** [comment]
@FreePhoenix888 claimed the reward of 300 RUB.
