### ISSUE TITLE
Hm... This is the norm?

### ISSUE THREAD

**Issue by uselessgoddess** [linksplatform/Data.Doublets#326]
https://github.com/linksplatform/Data.Doublets/blob/9b5fa41467808a2d570e6e65bc4df983dfe5f24e/rust/src/doublets/mem/splited/store.rs#L315

**Comment by uselessgoddess** [comment]
Also https://github.com/linksplatform/Data.Doublets/blob/9b5fa41467808a2d570e6e65bc4df983dfe5f24e/rust/src/doublets/mem/splited/store.rs#L476

**Comment by Konard** [comment]
I suggest use Constants here, this values can be redefined in theory.

**Comment by uselessgoddess** [comment]
I about it
