### ISSUE TITLE
Make `SizeInBytes` field constexpr instead of const

### ISSUE THREAD

**Issue by FreePhoenix888** [linksplatform/Data.Doublets#348]
https://github.com/linksplatform/Data.Doublets/blob/3675c2b02d0cea616db4f22673ffe43528681978/cpp/Platform.Data.Doublets/Memory/Split/RawLinkDataPart.h#L7-L7

**Comment by uselessgoddess** [comment]
Hm... replace `const` to `constexpr`

**Comment by FreePhoenix888** [comment]
> Hm... replace `const` to `constexpr`

You are genius

**Comment by uselessgoddess** [comment]
And `std::int64_t` to `std::size_t`
